// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/palettes/AuroraPurple.tsx": () => import("../components/mockups/palettes/AuroraPurple.tsx"),
  "./components/mockups/palettes/CyberGreen.tsx": () => import("../components/mockups/palettes/CyberGreen.tsx"),
  "./components/mockups/palettes/EmberAmber.tsx": () => import("../components/mockups/palettes/EmberAmber.tsx")
};
